local: &local
  host: localhost
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: almappdbuser
  password: dvl_123
  socket:  <%=
  ['/var/run/mysqld/mysqld.sock', # ubuntu/debian
   '/tmp/mysql.sock'].select { |f| File.exist? f }.first %>

development: &development
  database: almapp_development
  <<: *local

# Envrionments for the Devellocus continuous delivery pipeline.
# All inherit from "local", which specifies the correct socket
# file for MySQL, in addition to the same config as our local
# environemnt. All stages before Public use "test"

test: &test
  database: almapp_test
  <<: *local

production: &production
  database: almapp_production
  <<: *local
  # host: ec2-54-88-37-56.compute-1.amazonaws.com
  host: localhost
  # host: 172.31.20.173
  port: 3306

cucumber:
  <<: *test
