# source 'https://rubygems.org'
#
# # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
# gem 'rails', '4.2.3'
# # Use sqlite3 as the database for Active Record
# # gem 'sqlite3'
# # Use SCSS for stylesheets
# gem 'sass-rails', '~> 5.0'
# # Use Uglifier as compressor for JavaScript assets
# gem 'uglifier', '>= 1.3.0'
# # Use CoffeeScript for .coffee assets and views
# gem 'coffee-rails', '~> 4.1.0'
# # See https://github.com/rails/execjs#readme for more supported runtimes
# # gem 'therubyracer', platforms: :ruby
#
# # Use jquery as the JavaScript library
# gem 'jquery-rails'
# # Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
# gem 'turbolinks'
# # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.0'
# # bundle exec rake doc:rails generates the API under doc/api.
# gem 'sdoc', '~> 0.4.0', group: :doc
#
# # alma gems
# gem 'rally_api', '~> 1.2.0'
# gem 'devise', '~> 3.5.1'
# gem 'd3-rails', '~> 3.5.5'
# gem 'angularjs-rails', '~> 1.4.0'
#
# # angular with rails stuff
# gem 'mysql2', '~> 0.3.18'
# gem 'bower-rails', '~> 0.10.0'
# gem 'angular-rails-templates', '~> 0.2.0'
# gem 'sprockets', '~> 2.12.4' #angular rails depends on sprockets 2.0 do not upgrade to 3.0+
#
# # heroku stuff
# gem "foreman"
# group :production, :staging do
#   gem "rails_12factor"
#   gem 'pg', '0.15.1'
#   gem "rails_stdout_logging"
#   gem "rails_serve_static_assets"
# end


# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development



source 'https://rubygems.org'

ruby "2.2.0"
#ruby-gemset=sample

#gem 'rails', '4.0.4'
gem 'rake'
gem 'term-ansicolor'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'jquery-rails'
gem 'sass', '3.4.15'
# alma gems
gem 'rally_api', '~> 1.2.0'
gem 'devise', '~> 3.5.1'
gem 'd3-rails', '~> 3.5.5'
gem 'angularjs-rails', '~> 1.4.0'

# angular with rails stuff
gem 'mysql2', '~> 0.3.18'
gem 'bower-rails', '~> 0.10.0'
gem 'angular-rails-templates', '~> 0.2.0'
gem 'sprockets', '~> 2.12.4' #angular rails depends on sprockets 2.0 do not upgrade to 3.0+

# group :test, :development do
#   gem "rspec-rails", "~> 2.0"
#   gem "factory_girl_rails", "~> 4.0"
#   gem "capybara"
#   gem "database_cleaner"
#   gem "selenium-webdriver"
# end

group :markup do
  gem 'coffee-rails', '~> 4.0.0'
  gem 'uglifier', '>= 1.3.0'
end

group :styling do
  gem 'compass', '>= 0.12.2'
  gem 'compass-rails', '>= 1.0.3'
  gem 'sass-rails', '~> 4.0.0'
end

group :capistrano do
  gem 'capistrano',           '~> 3.1.0'
  gem 'capistrano-rails',     '~> 1.1', require: false
  gem 'capistrano-bundler',   '~> 1.1', require: false
  gem 'formatador',           '~> 0.2.4'
  gem 'terminal-table'
end

group :cucumber do
  gem 'cucumber-rails', require: false
end

group :test do
	gem 'rspec-expectations'
	gem 'minitest'
  gem 'minitest-rails'
  gem 'capybara'
  gem 'minitest-focus'
  gem 'minitest-reporters'
  gem 'database_cleaner'
  gem 'turn', require: false
  gem 'mocha', require: false
end

group :doc do
  gem 'sdoc', require: false
end
